logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8888
spring:
  datasource:
    password: pass
    url: jdbc:postgresql://127.0.0.1:5444/mibandtoolsdb
    username: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  flyway:
    baseline-on-migrate: true

app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

